### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by Nyariki** [acefalobi/android-stepper#28]
Got a Failed to resolve: com.github.acefalobi:android-stepper:0.3.0 on a new android project. So I thought something was wrong on my end. But looking at [jitpack](https://jitpack.io/com/github/acefalobi/android-stepper/), I can only see up to version 0.2.2 there. 

Please let meknow if there's something I'm missing.

**Comment by MartinMbae** [comment]
Also facing the same issue. I ended up using 0.2.2

**Comment by acefalobi** [comment]
Oh this is odd. Will look into it

**Comment by Romaine001** [comment]
Any update on the failed resolution for 0.3.0 with the setTextAppearance fix

**Comment by lorenzoSpacelens** [comment]
Any update?

**Comment by dariush-fathie** [comment]
Any update?

**Comment by massivemadness** [comment]
@acefalobi please fix this

**Comment by EslamWaheed** [comment]
Any update?

**Comment by Sherzodbek-Muhammadiev** [comment]
Could not find com.github.acefalobi:android-stepper:v0.2.2.

Could not find com.github.acefalobi:android-stepper:.0.3.0.

**Comment by perqin** [comment]
It seems that there's typo in the version. `com.github.acefalobi:android-stepper:v.0.3.0` works for me.

By the way, there's also a version `.0.3.0` which seems to be built from the same commit.

**Comment by acefalobi** [comment]
Update: this has been fixed now. Like @perqin said, it was an issue with a typo in the release tag. Fetching from `com.github.acefalobi:android-stepper:0.3.0` should be good now. Please confirm that it is fixed so I can close

**Comment by asantivanezg** [comment]
@acefalobi still facing the same problem  Failed to resolve: com.github.acefalobi:android-stepper:0.3.0

**Comment by acefalobi** [comment]
@zwingloo check the spelling, your internet, and that the jitpack maven repository is added to your project.

Jitpack shows the pom as available so it's likely one of those reasons: https://jitpack.io/com/github/acefalobi/android-stepper/0.3.0/android-stepper-0.3.0.pom
